
.PHONY: all
all:
	@echo "done"

.PHONY: check
check:
	@echo "done"

.PHONY: install
install:
	install -d $(DESTDIR)/usr/share/man/man8
	install --mode=0644 gentoo-oam.8 $(DESTDIR)/usr/share/man/man8/
