
.PHONY: all
all:
	@echo "done"

.PHONY: check
check:
	@echo "done"

.PHONY: install
install:
	install -d $(DESTDIR)/usr/share/man/man8 $(DESTDIR)/usr/share/man/man1
	install --mode=0644 gentoo-oam.8 $(DESTDIR)/usr/share/man/man8/
	install --mode=0644 oam-flow.8 $(DESTDIR)/usr/share/man/man8/
	install --mode=0644 oam-watch.8 $(DESTDIR)/usr/share/man/man8/
