.\" Manpage for oam
.TH man 8 "10 July 2015" "1.0" "oam flow man page"

.SH NAME
oam flow \- workflow runner for a gentoo server

.SH SYNOPSIS
oam flow [-d] flowname \- run a specified flow

oam step [-d] stepname \- run a specified step

.SH DESCRIPTION

An flow is made up of an ordered list of stages.
Each stage can have one or more steps which are actions run in parallel.
.PP
Steps can optionally be:
.P
.IP \(bu
run on remote servers (via ssh - password-less key setup required)
.P
.IP \(bu
run detached (the flow will not wait for the action to complete before starting the next stage).

.PP
An example flow definition
.PP
.RS 0
        sync
.RS 0
        glsa
.RS 0
        fetch
.RS 0
        update
.RS 0
        qcheck
.PP
In this example the stages run one-after-the-other.
.PP
The stages/steps for a flow are defined in: /etc/oam/oam.yaml

.SH FILES

.TP
.BI /etc/oam/oam.yaml
oam system configuration

.SH BUGS
None.

.SH SEE ALSO
oam(8), emaint(1), emerge(1), eclean(1), glsa-check(1), qcheck(1), logrotate(8),
eix(1), genlop(1), ts(1), multitail(1)

.SH AUTHOR
Paul Healy

.SH COPYRIGHT
GNU GENERAL PUBLIC LICENSE Version 2
