.\" Manpage for gentoo-oam
.TH man 8 "10 May 2015" "1.0" "gentoo-oam man page"

.SH NAME
gentoo-oam \- workflow helpers for a gentoo server

.SH SYNOPSIS
oam-expire \- prune old log files produced by the gentoo-oam scripts

oam-fetch \- fetch package sources prior to compilation/installation

oam-genlop \- wrapper around genlop

oam-glsa \- wrapper around glsa-check

oam-qcheck \- runs qcheck and produces a summary of files with potential problems

oam-sync \- run a set of sync actions

oam-unmask-write \- run an emerge update operation with --autounmask-write set to 'y'

oam-update \- run a normal set of emerge update actions

oam-uptime \- writes a short system loadavg to the console

oam-version \- write the gentoo-oam version to the console

oam-watch \- watch the various files and status of an update cycle using multitail(1)

oam-weekly \- run sync and update actions (actions defined in /etc/gentoo-oam.conf)

.SH DESCRIPTION
The gentoo-oam scripts build on portage utilities to automate some common
sys-admin tasks. They delegate most of the actual work to the normal
portage tools.
.P
.IP \(bu
Common tasks are automated (e.g. weekly update, overlays sync... etc)
.IP \(bu
Everything is logged (under /var/log/oam), and logrotate'd.
.IP \(bu
Overview of actions provided by oam-watch (built on multitail(1) )
.IP \(bu
Central configuration is taken from /etc/gentoo-oam.conf
.IP \(bu
The package also acts as a meta package pulling in some very useful portage
utilities (e.g. eix, glsa-check... etc)
.P
The default weekly action list (run by
.B oam-weekly
using OAM_WEEKLY setting in /etc/gentoo-oam.conf) is:
.PP
.RS 0
        oam-sync
.RS 0
        oam-glsa
.RS 0
        oam-fetch
.RS 0
        oam-update
.RS 0
        oam-qcheck
.P
The
.B oam-sync script runs these actions in sequence:
.P
.IP \(bu
emaint --auto sync
.IP \(bu
layman --sync=ALL (only if layman is installed)
.IP \(bu
eix-update
.IP \(bu
eix-remote update1 (only if layman is installed)
.IP \(bu
eix-remote add1 (only if layman is installed)
.P
The
.B oam-watch
script can be used to montor a currently running operation.
The multi-pane UI is provided by multitail(1).
To run oam-watch as a non-root user (recommended), add the user to the portage group and add /usr/sbin to its PATH.
Hit 'b' to select a window and then browse the multitail(1) scrollback buffer.
Exit the program by typing: <control>-C
.P
The
.B oam-glsa
script simply runs glsa-check, logging the results to /var/log/oam/glsa.log. The
script return 1 if that file is non-empty, 0 otherwise.
.P
The
.B oam-fetch
script simply runs emerge --fetchonly to pull down source packages prior to installation
proper.
.P
The
.B oam-update script runs these actions in sequence:
.P
.IP \(bu
emerge world
.IP \(bu
revdep-rebuild
.IP \(bu
python-updater
.IP \(bu
perl-cleaner (if it is installed)
.IP \(bu
emerge @preserved-rebuild (if there are preserved libraries)
.IP \(bu
eclean distfiles (if the OAM_CLEAN_DISTFILES setting is 1)
.P
The
.B oam-qcheck
script runs qcheck(1), saving all AFK and MD5-DIGEST failures to a (daily) file under
/var/log/oam/qcheck.

The
.B oam-expire
script is called by the installed logrotate control settings. See the OAM_KEEPLOGS and
OAM_QCHECKKEEPLOGS settings.

The
.B oam-unmask-write
scripts runs with oam-fetch script with '--autounmask-write y' set.

The
.B oam-genlop
script is a wrapper called by oam-watch to filter the output of 'genlop -c'. See
man genlop(1) / FEATURES if there never seems to be a merge running.

The
.B oam-version
simply prints the version of the gentoo-oam scripts to stdout.
.P

.SH SYSTEM SETTINGS

These settings control the operation of gentoo-oam and are set in /etc/gentoo-oam.conf:
.TP
.BI OAM_EMERGE_OPTS
The parameters passed to emerge for update. Defaults to "--backtrack=50 --deep -v"
.TP
.BI OAM_EMERGE_SYNC
Used to decide if emerge --sync should be run (for example you may not want to
run it if the /usr/portage/distfiles is nfs mounted from another server).
Defaults to 1
.TP
.BI OAM_CLEAN_DISTFILES
Used to decide if eclean distfiles should be run (for example you may not want to
run it if the /usr/portage/distfiles is nfs mounted from another server). Defaults to 1
.TP
.BI OAM_WEEKLY
The actions to perform when the oam-weekly is run. Defaults to "oam-sync oam-glsa oam-fetch oam-update oam-qcheck "
.TP
.BI OAM_LOGDIR
The location where gentoo-oam logs will be sent/stored. Defaults to /var/log/oam
.TP
.BI OAM_KEEPLOGS
The number of sync/update log sets to keep. Defaults to 10
.TP
.BI OAM_QCHECKDIR
The location where qcheck log summaries will be stored. Defaults to /var/log/oam/qcheck
.TP
.BI OAM_QCHECKKEEPLOGS
The number of old qcheck logs to keep. Defaults to 10
.TP
.BI OAM_TS
The date/time format used by gentoo-oam for logging. Defaults to "%Y%m%d:%H:%M:%S"
.TP
.BI OAM_HEARTBEATSLEEP
How long to sleep between printing out the load average and gelop(1) output. Defaults to 60 (seconds).
.TP
.BI OAM_SANDBOXWAIT
How long to wait for the sandbox process to appear before trying to run genlop(1).

.SH WORKFLOW

As an example, to add a new "local" workflow:
.TP
.BI /usr/local/sbin/oam-local
Create the new workflow script by copying the oam-weekly script: cp /usr/sbin/oam-weekly /usr/local/sbin/oam-local
.TP
.BI /etc/gentoo-oam.d/oam-local.conf
Add the required steps to a new OAM_LOCAL variable defined in: /etc/gentoo-oam.d/oam-local.conf
Note the underscore required in the variable and the minus sign in the configuration file name.
Other settings which need to be specific to this new workflow can be added to this newly created
configuration file and they will override the system settings found in /etc/gentoo-oam.conf
.P
Non gentoo-oam steps can be added to the new workflow provided that:
.IP \(bu
The step can be executed as a program requiring no arguments (note that environment variables can be set/exported
in the workflow configuration file); e.g. "/usr/local/bin/localbackup.sh"
.IP \(bu
The step should ideally handle its own logging (in this case gentoo-oam capture output to /var/oam/oam-local.log).
.IP \(bu
The step should return 0 to indicate that the action succeeded. If it returns a non-zero result then the
workflow will be aborted at that point.
.P
Example OAM_LOCAL setting in /etc/gentoo-oam.d/oam-local.conf (with made up scripts being called):
.PP
.RS 0
OAM_LOCAL="
.RS 0
	depclean-pretend.sh
.RS 0
	localdumpfs.sh
.RS 0
	rdumpfs-rota-daily
.RS 0
	smartctl-start.sh
"

.SH FILES

.TP
.BI /etc/gentoo-oam.conf
gentoo-oam system configuration
.TP
.BI /var/log/oam/error.log
central locations for error reports
.TP
.BI /var/log/oam/glsa.log
results of a glsa-check(1) run following a sync
.TP
.BI /var/log/oam/oam.log
log of oam operations started/stopped
.TP
.BI /var/log/oam/DATE/blocks.log
log of the errors reported by emerge fetch operation (typically blocks) for one particular day
.TP
.BI /var/log/oam/DATE/merge.log
log of the emerge for one particular day
.TP
.BI /var/log/oam/DATE/sync.log
log of the oam-sync operation for one particular day
.TP
.BI /usr/share/gentoo-oam/gentoo-oam-functions.sh
common shell functions called by the various oam scripts
.TP
.BI /usr/share/gentoo-oam/gentoo-oam-multitail.conf
some system wide configuration for multitail(1) when called from oam-watch

.SH HELPER PROGRAMS

These oam log files can be viewed while running oam-watch:
.TP
.BI /var/log/oam/DATE/blocks.log
by default this file can be viewed from oam-watch when <control>b is pressed
.TP
.BI /var/log/oam/error.log
by default this file can be viewed from oam-watch when <control>e is pressed
.TP
.BI /var/log/oam/glsa.log
by default this file can be viewed from oam-watch when <control>g is pressed
.TP
.BI /var/log/oam/DATE/merge.log
by default this file can be viewed from oam-watch when <control>r is pressed
.TP
.BI /var/log/oam/oam.log
by default this file can be viewed from oam-watch when <control>o is pressed
.TP
.BI /var/log/oam/DATE/sync.log
by default this file can be viewed from oam-watch when <control>y is pressed
.P
These environment settings are required for the external viewing function:
.TP
.BI DISPLAY
A new xterm(1) is run to view each log file - so DISPLAY must be set appropriately.
.TP
.BI EDITOR
the EDITOR setting is used as viewing program.

In addition the /var/log/oam directory tree can be browsed by ranger(1) if
that is installed when <control>n is pressed while in oam-watch(1).

.SH BUGS
Some actions (e.g. emaint, emerge... etc) buffer output. As a result
oam-watch may not show anything going on for long periods.
.P
The perl-cleaner stdout needs more ansi control character filtering.
.P
oam-watch takes two control-C's to exit (pipe stuff).

.SH SEE ALSO
emaint(1), emerge(1), eclean(1), glsa-check(1), qcheck(1), logrotate(8),
eix(1), genlop(1), ts(1), multitail(1)

.SH AUTHOR
Paul Healy

.SH COPYRIGHT
GNU GENERAL PUBLIC LICENSE Version 2
