.\" Manpage for gentoo-oam
.TH man 8 "10 May 2015" "1.0" "gentoo-oam man page"

.SH NAME
gentoo-oam \- workflow helpers for a gentoo server

.SH SYNOPSIS
oam-expire \- prune old log files produced by the gentoo-oam scripts

oam-fetch \- fetch package sources prior to compilation/installation

oam-genlop-current \- wrapper around genlop called by oam-watch

oam-glsa \- wrapper around glsa-check

oam-qcheck \- runs qcheck and produces a summary of files with potential problems

oam-sync \- run a set of sync actions

oam-unmask-write \- run an emerge update operation with --autounmask-write set to 'y'

oam-update \- run a normal set of emerge update actions

oam-uptime \- writes a short system loadavg to the console

oam-version \- write the gentoo-oam version to the console

oam-watch \- watch the various files and status of an update cycle using multitail(1)

oam-weekly \- run sync and update actions (actions defined in /etc/gentoo-oam.conf)

.SH DESCRIPTION
The gentoo-oam scripts build on portage utilities to automate some common
sys-admin tasks. They delegate most of the actual work to the normal
portage tools.
.P
.IP \(bu
Common tasks are automated (e.g. weekly update, overlays sync... etc)
.IP \(bu
Everything is logged (under /var/log/oam), and logrotate'd.
.IP \(bu
Overview of actions provided by oam-watch (built on multitail(1) )
.IP \(bu
Central configuration is taken from /etc/gentoo-oam.conf
.IP \(bu
The package also acts as a meta package pulling in some very useful portage
utilities (e.g. eix, glsa-check... etc)
.P
The default weekly action list (run by
.B oam-weekly
using OAM_WEEKLY setting in /etc/gentoo-oam.conf) is:
.PP
.RS 0
        oam-sync
.RS 0
        oam-glsa
.RS 0
        oam-fetch
.RS 0
        oam-update
.RS 0
        oam-qcheck
.P
The
.B oam-sync script runs these actions in sequence:
.P
.IP \(bu
emaint --auto sync
.IP \(bu
layman --sync=ALL (only if layman is installed)
.IP \(bu
eix-update
.IP \(bu
eix-remote update1 (only if layman is installed)
.IP \(bu
eix-remote add1 (only if layman is installed)
.P
The
.B oam-watch
script can be used to watch a currently running operation. It provides a snapshot
of the current sync/update... etc The UI is provided by multitail(1). To run this
script as a non-root user (recommended), add that user to the portage group. Also
add /usr/sbin to the PATH (required for genlop). Hit 'b' to select a window and
then browse the multitail(1) scrollback buffer.
.P
The
.B oam-glsa
script simply runs glsa-check, logging the results to /var/log/oam/glsa.log. The
script return 1 if that file is non-empty, 0 otherwise.
.P
The
.B oam-fetch
script simply runs emerge --fetchonly to pull down source packages prior to installation
proper.
.P
The
.B oam-update script runs these actions in sequence:
.P
.IP \(bu
emerge world
.IP \(bu
revdep-rebuild
.IP \(bu
python-updater
.IP \(bu
perl-cleaner (if it is installed)
.IP \(bu
emerge @preserved-rebuild (if there are preserved libraries)
.IP \(bu
eclean distfiles (if the OAM_CLEAN_DISTFILES setting is 1)
.P
The
.B oam-qcheck
script runs qcheck(1), saving all AFK and MD5-DIGEST failures to a (daily) file under
/var/log/oam/qcheck.

The
.B oam-expire
script is called by the installed logrotate control settings. See the OAM_KEEPLOGS and
OAM_QCHECKKEEPLOGS settings.

The
.B oam-unmask-write
scripts runs with oam-fetch script with '--autounmask-write y' set.

The
.B oam-genlop-current
script is a wrapper called by oam-watch to filter the output of 'genlop -c'. See
man genlop(1) / FEATURES if there never seems to be a merge running.

The
.B oam-version
simply prints the version of the gentoo-oam scripts to stdout.
.P
These settings control the operation of gentoo-oam and are set in /etc/gentoo-oam.conf:
.TP
.BI OAM_EMERGE_OPTS
The parameters passed to emerge for update. Defaults to "--backtrack=50 --deep -v"
.TP
.BI OAM_CLEAN_DISTFILES
Used to decide if eclean distfiles should be run (for example you may not want to
run it if the /usr/portage/distfiles is nfs mounted from another server). Defaults to 1
.TP
.BI OAM_WEEKLY
The actions to perform when the oam-weekly is run. Defaults to "oam-sync oam-glsa oam-fetch oam-update oam-qcheck "
.TP
.BI OAM_LOGDIR
The location where gentoo-oam logs will be sent/stored. Defaults to /var/log/oam
.TP
.BI OAM_KEEPLOGS
The number of sync/update log sets to keep. Defaults to 10
.TP
.BI OAM_QCHECKDIR
The location where qcheck log summaries will be stored. Defaults to /var/log/oam/qcheck
.TP
.BI OAM_QCHECKKEEPLOGS
The number of old qcheck logs to keep. Defaults to 10
.TP
.BI OAM_TS
The date/time format used by gentoo-oam for logging. Defaults to "%Y%m%d:%H:%M:%S"
.TP
.BI OAM_HEARTBEATSLEEP
How long to sleep between printing out the load average and gelop(1) output. Defaults to 60 (seconds).
.TP
.BI OAM_SANDBOXWAIT
How long to wait for the sandbox process to appear before trying to run genlop(1).

.SH FILES

/etc/gentoo-oam.conf \- gentoo-oam system configuration

/var/log/oam/oam.log \- log of oam operations started/stopped

/var/log/oam/error.log \- central locations for error reports

/var/log/oam/glsa.log \- results of a glsa-check(1) run following a sync

.SH BUGS
Some actions (e.g. emaint, emerge... etc) buffer output. As a result
oam-watch may not show anything going on for long periods.
.P
The perl-cleaner stdout needs more ansi control character filtering.
.P
oam-watch takes two control-C's to exit (pipe stuff).

.SH SEE ALSO
emaint(1), emerge(1), eclean(1), glsa-check(1), qcheck(1), logrotate(8),
eix(1), genlop(1), ts(1), multitail(1)

.SH AUTHOR
Paul Healy

.SH COPYRIGHT
GNU GENERAL PUBLIC LICENSE Version 2
