#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

LOGPREFIX=$OAM_LOGDIR/$(date +%Y%m%d)

[[ ! -d $LOGPREFIX ]] && mkdir -p $LOGPREFIX

if [[ "$OAM_CLEAN_DISTFILES" = "1" ]] ; then
    oam_log "eclean-distfiles start"
    eclean --nocolor distfiles \
       > >(oam_logphase "eclean" ${LOGPREFIX}/merge.log) \
       2> >(oam_stripansi | oam_err "eclean")
    oam_log "eclean-distfiles complete"
fi

if [[ "$OAM_CLEAN_KERNEL" = "1" ]] ; then
    oam_log "eclean-kernel start"
    eclean-kernel $OAM_ECLEAN_KERNEL
    oam_log "eclean-kernel complete"
fi

exit 0
