#!/bin/bash

source /etc/gentoo-oam.conf || oam_die "/etc/gentoo-oam.conf missing - exiting"
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

echo "$(oam_ts) $(cat /proc/loadavg | awk '{print $1 " " $2 " " $3}')"

exit 0
