#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

LOGPREFIX=$OAM_LOGDIR/$(date +%Y%m%d)

[[ ! -d "$LOGPREFIX" ]] && mkdir -p $LOGPREFIX
[[ ! -d "$OAM_QCHECKDIR" ]] && mkdir -p $OAM_QCHECKDIR

oam_log "qcheck start"

(
    qcheck --all --nomtime --nocolor | \
	egrep 'AKF|MD5-DIGEST' | \
	sort > $OAM_QCHECKDIR/$(date +%Y%m%d).log
) \
       2> >(oam_err "qcheck")

oam_log "qcheck complete"

exit 0
