#!/usr/bin/python2 -u

import subprocess
import os
from datetime import datetime
import sys

p = subprocess.Popen(['tail', '-F', '/var/log/emerge.log'], stdout=subprocess.PIPE)
ts_format = os.getenv('OAM_TS', '%Y%m%d:%H:%M:%S')

while 1:
    line = p.stdout.readline()
    field = line.split(':', 1)
    print datetime.fromtimestamp(int(field[0])).strftime(ts_format), field[1],

sys.exit(0)
