#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

LOGPREFIX=$OAM_LOGDIR/$(date +%Y%m%d)

[[ ! -d $LOGPREFIX ]] && mkdir -p $LOGPREFIX

oam_log "oam-sync start"

emaint --auto sync \
       >>${LOGPREFIX}/sync.log \
       2> >(oam_err "sync")

layman --sync=ALL --nocolor \
       >>${LOGPREFIX}/layman.log \
       2> >(oam_err "layman")

eix-update --nocolor \
       >>${LOGPREFIX}/eix-update.log \
       2> >(oam_err "eix-update")

# eix-remote update1 spams the error log
eix-remote update1 \
       >>${LOGPREFIX}/eix-remote-update1.log \
       2>&1

# eix-remote add1 spams the error log
eix-remote add1 \
       >>${LOGPREFIX}/eix-remote-add1.log \
       2>&1

# slightly useful as a record of changes - not sure/may remove
eix-diff --nocolor \
       >>${LOGPREFIX}/eix-diff.log \
       2> >(oam_err "eix-diff")

oam_log "oam-sync complete"

exit 0
