#!/bin/bash

source /etc/gentoo-oam.conf || oam_die "/etc/gentoo-oam.conf missing - exiting"
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

oam_genlop_filter()
{
    read empty
    read currently merging num out of total
    read empty
    read start package
    read empty
    read current merge time runtime
    read eta estimatetime

    if [[ "$currently" = "Currently" ]] ; then
	echo -e "$(oam_ts) $num/$total pkgs\n  $package \n  Gone: $runtime \n  Left: $estimatetime" | \
	    sed -e 's/minutes/min/g;s/seconds./sec/g;s/hour/hr/g;s/ and / /g'
    fi
}

echo "$(oam_ts) oam-watch started"

while /bin/true; do
    inotifywait --timeout $OAM_HEARTBEATSLEEP --quiet --event modify /var/log/emerge.log
    case "$?" in
	0)
	    sleep 1
	    [[ -n "$(pgrep sandbox)" ]] && \
		genlop --nocolor --current | oam_genlop_filter
            ;;
	1)
	    echo "$(oam_ts) /var/log/emerge.log was removed"
            ;;
	2)
	    oam-uptime
            ;;
	*)
	    echo "$(oam_ts) inotifywait exited with $?"
            ;;
    esac
done

exit 0
