#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

LOGPREFIX=$OAM_LOGDIR/$(date +%Y%m%d)

[[ ! -d $LOGPREFIX ]] && mkdir -p $LOGPREFIX

oam_log "oam-fetch start $*"

emerge --fetchonly --update $OAM_EMERGE_OPTS $@ world \
       >>${LOGPREFIX}/fetch.log \
       2> >(oam_err "fetch")

oam_log "oam-fetch complete"

exit 0
