#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

oam_log "oam-unmask-write start"

oam-fetch --autounmask-write y

oam_log "oam-unmask-write stop"

exit 0
