#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

set -e

[[ ! -d $OAM_LOGDIR ]] && mkdir -p $OAM_LOGDIR

scriptname=$(basename $0)
steps=${scriptname^^}
steps=${steps/-/_}

oam_log "$scriptname start"

for op in ${!steps} ; do
    $op || oam_die "$op failed - exiting $scriptname"
done

oam_log "$scriptname stop"

exit 0
