#!/bin/bash

source /etc/gentoo-oam.conf || oam_die "/etc/gentoo-oam.conf missing - exiting"
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

cd $OAM_LOGDIR || oam_die "/var/log/oam is missing - exiting"

LOGDATE=$(ls -1dt 2* | head -1)

if [[ -z "$LOGDATE" ]] ; then
    LOGDATE=$(date +%Y%m%d)
    mkdir -p $LOGDATE
fi

TOPLOGFILES="error glsa oam 
	$LOGDATE/sync $LOGDATE/fetch $LOGDATE/update $LOGDATE/blocks"

if [[ $(id -u) -eq 0 ]] ; then
    for f in $TOPLOGFILES ; do
	[[ ! -f ${f}.log ]] && touch ${f}.log
    done
fi

oam-genlop-current | \
    multitail \
	  -x "$HOSTNAME/oam/$LOGDATE gentoo-oam Version $(oam_version)" \
	  --config /usr/share/gentoo-oam/gentoo-oam-multitail.conf \
	  --basename \
	  -sw 45,40 -sn 2,3 \
	  \
	  -wh 12 oam.log \
	  -j \
	  \
	  -i $LOGDATE/sync.log \
	  -I $LOGDATE/merge.log \
	  -I $LOGDATE/blocks.log \
	  -wh 8 error.log \
	  -wh 4 -ci red glsa.log

exit 0
