#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

[[ ! -d $OAM_LOGDIR ]] && mkdir -p $OAM_LOGDIR

oam_log "oam-weekly start"

for op in $OAM_WEEKLY ; do
    $op
done

oam_log "oam-weekly stop"

exit 0
