#!/bin/bash

source /etc/gentoo-oam.conf || oam_die "/etc/gentoo-oam.conf missing - exiting"
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

cd $OAM_LOGDIR || oam_die "/var/log/oam is missing - exiting"

LOGDATE=$(ls -1dt 2* | head -1)

if [[ -z "$LOGDATE" ]] ; then
    LOGDATE=$(date +%Y%m%d)
    mkdir -p $LOGDATE
fi

TOPLOGFILES="error glsa oam"

for f in $TOPLOGFILES ; do
    [[ ! -f ${f}.log ]] && touch ${f}.log
done

multitail -x $HOSTNAME/oam/$LOGDATE \
	  -T --basename \
	  -ts --mergeall -iw $LOGDATE/\*.log 2 \
	  --no-mergeall \
	  -wh 4 error.log \
	  -wh 4 -ci red glsa.log \
	  -wh 4 oam.log \
	  -wh 1 -r 30 -l uptime \
	  -wh 6 -rc 60 -l oam-genlop-current

exit 0
