#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

LOGPREFIX=$OAM_LOGDIR/$(date +%Y%m%d)

[[ ! -d $LOGPREFIX ]] && mkdir -p $LOGPREFIX

OAM_TAG=update \
       oam-merge --keep-going --update $OAM_EMERGE_OPTS world

oam_log "revdep-rebuild start"
revdep-rebuild --nocolor --ignore \
       >>${LOGPREFIX}/merge.log \
       2> >(oam_err "revdep")

oam_log "python-updater start"
[ -x /usr/sbin/python-updater ] && \
    python-updater -eall \
       >>${LOGPREFIX}/merge.log \
       2> >(oam_stripansi | oam_err "python")

oam_log "perl-cleaner start"
[[ -x /usr/sbin/perl-cleaner ]] && \
    perl-cleaner --all \
       >>${LOGPREFIX}/merge.log \
       2> >(oam_stripansi | oam_err "perl")

[[ -n "$(portageq list_preserved_libs / )" ]] && \
    OAM_TAG=preserved \
	   oam-merge --keep-going --verbose @preserved-rebuild

if [[ "$OAM_CLEAN_DISTFILES" = "1" ]] ; then
    oam_log "eclean-distfiles start"
    eclean --nocolor distfiles \
       > >(oam_logphase "eclean" ${LOGPREFIX}/merge.log) \
       2> >(oam_stripansi | oam_err "eclean")
fi

oam_log "oam-update complete"

exit 0
