#!/bin/bash

if [ -z "$LANG" ] ; then
    LANG="$(eselect locale show | tail -1| xargs)"
    if [ "${LANG}" = "(none)" -o "${LANG}" = "C" ] ; then
	LANG="C.UTF-8"
    fi
fi

export LANG

exec /usr/bin/oam expire >>/var/log/oam/expire.log 2>&1
