#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

tag=${OAM_TAG:-"merge"}

oam_log "oam ${tag} start $*"

emerge $@ \
       >>$(oam_logfile merge) \
       2>>$(oam_logfile blocks)

oam_log "oam ${tag} complete"

exit 0
