#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

OAM_TAG=newuse \
       oam-merge --update --newuse --deep --verbose $@ world

OAM_TAG=depclean \
       oam-merge --pretend --depclean --verbose $@ world

exit 0
