#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

oamfile=$(oam_logfile oam)

cd $(dirname $oamfile) || oam_die "failed to chdir to $(dirname $oamfile)"

while true ; do
    case $1 in
	-c)
            cmd=$2
            shift 2
            ;;
	-d)
            musshdebug="-d 1"
            shift
            ;;
	-l)
            loginname=$2
            shift 2
            ;;
	-s) # start in detached mode, with output logging
            screencmdprefix="screen -d -m -L -S oam-mussh"
            shift
            ;;
	*)
            break
            ;;
    esac
done

mussh="$screencmdprefix mussh $musshdebug -m -o ConnectTimeout=5"
mussh="$mussh -l ${loginname:-"$USER"} -c "${cmd:-"oam-go"}" -h $@"

oam_log "running: $mussh"

$mussh &>> $oamfile

exit 0

    

