#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

echo "$(oam_ts) oam-expire start" >>$OAM_LOGDIR/expire.log

if [[ -d $OAM_QCHECKDIR ]] ; then
    cd $OAM_QCHECKDIR && \
    ls -1tr | head -n -$OAM_QCHECKKEEPLOGS | xargs --verbose -d '\n' rm -f >>$OAM_LOGDIR/expire.log 2>&1
fi

if [[ -d $OAM_LOGDIR ]] ; then
    cd $OAM_LOGDIR && \
    ls -d1tr 2* | head -n -$OAM_KEEPLOGS | xargs --verbose -d '\n' rm -rf >>$OAM_LOGDIR/expire.log 2>&1
fi

echo "$(oam_ts) oam-expire complete" >>$OAM_LOGDIR/expire.log

exit 0
