#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

syncfile=$(oam_logfile sync)
logfile=$(oam_logfile merge)

if [[ -f $syncfile ]] && grep -q 'An update to portage is available' $syncfile ; then
    oam_log "updating sys-apps/portage"
    OAM_TAG=portage \
	   oam-merge --update --verbose --verbose-conflicts sys-apps/portage
fi

OAM_TAG=update \
       oam-merge --keep-going --update $OAM_EMERGE_OPTS world

oam_log "revdep-rebuild start"
revdep-rebuild --nocolor --ignore \
       >>$logfile \
       2> >(oam_err "revdep")

oam_log "python-updater start: $(oam changed dev-lang/python)"
if [[ -x /usr/sbin/python-updater ]] ; then
    # Todo filter:
    # python-updater /usr/sbin/python-updater: line 752: /var/db/pkg/x11-themes/sound-theme-freedesktop-0.8/RDEPEND: No such file or directory
    python-updater -eall \
       > >(oam_stripansi >> $logfile) \
       2> >(oam_stripansi | oam_err "python-updater")
    oam changed --update dev-lang/python
fi

oam_log "perl-cleaner start: $(oam changed dev-lang/perl)"
if [[ "$OAM_PERL_CLEANER" -eq 1 && -x /usr/sbin/perl-cleaner ]] ; then
    # Todo filter:
    # perl-cleaner Can't open machine/ansi.h: No such file or directory
    # perl-cleaner Can't open gnu/stubs-x32.h: No such file or directory
    perl-cleaner --all \
       > >(oam_stripansi >> $logfile) \
       2> >(oam_stripansi | oam_err "perl-cleaner")
    oam changed --update dev-lang/perl
fi

[[ -n "$(portageq list_preserved_libs / )" ]] && \
    OAM_TAG=preserved \
	   oam-merge --keep-going --verbose @preserved-rebuild

oam_log "oam-update complete"

exit 0
