#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

for i in {1..2} ; do
    OAM_TAG=system_${i} \
	   oam-merge --keep-going --verbose @system
done

OAM_TAG=emptytree \
       I_KNOW_WHAT_I_AM_DOING=1 \
       oam-merge --keep-going --emptytree --verbose world

exit 0
