#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

deplog=$(oam_logfile depclean)
cleanpkgs=$(oam_logfile cleanpkgs)
logfile=$(oam_logfile merge)

oam_log "oam-unused start $*"

case "$1" in
    build|newuse)
	oam-newuse
	;;
    depclean)
	emerge --pretend --depclean --with-bdeps=y --verbose \
	       >$deplog 2>&1
	if grep "Dependencies could not be completely resolved" $deplog ; then
	    echo "depclean check failed - see $deplog" | oam_err "depclean"
	fi
	;;
    list)
	grep "All selected packages:" $deplog | \
	    sed -E -e 's/All selected packages://' -e "s/ /\n/g" | \
	    sort >$cleanpkgs
	oam_log "oam-unused pkg candidates for removal are in $cleanpkgs"
	;;
    run)
	$0 newuse
	$0 depclean
	$0 list
	;;
    remove)
	oam_log "oam-unused in 5 seconds, removing $(cat $cleanpkgs)"
	sleep 5
	emerge --depclean --verbose $(cat $cleanpkgs) >>$logfile 2>&1
	oam_log "revdep-rebuild start"
	revdep-rebuild --nocolor --ignore \
		       >>$logfile \
		       2> >(oam_err "revdep")
	;;
    *)
	echo "usage: $(basename $0) newuse|depclean|list|remove"
	;;
esac

oam_log "oam-unused complete"

exit 0
