#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

[[ ! -d $OAM_LOGDIR ]] && mkdir -p $OAM_LOGDIR

scriptname=$(basename $0)
steps=${scriptname^^}
steps=${steps/-/_}

oam_log "$scriptname start"

for op in ${!steps} ; do
    $op >>$OAM_LOGDIR/${scriptname}.log 2>&1
    result=$?
    if [[ $result -ne 0 ]] ; then
	oam_log "$scriptname failed at $op, return code=$result"
	if [[ -n "$OAM_ONERROR" ]] ; then
	    oam_log "running: $OAM_ONERROR $scriptname $op $result"
	    $OAM_ONERROR $scriptname $op $result >>$OAM_LOGDIR/${scriptname}.log 2>&1
	    if [[ $? -eq 7 ]] ; then
		oam_log "$OAM_ONERROR has requested workflow continuation"
		continue
	    fi
	fi
	[[ $result -ne 7 ]] && oam_die "$op failed - exiting $scriptname"
    fi
done

oam_log "$scriptname stop"

exit 0
