#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

oam_log "qcheck start"

(
    qcheck --all --nomtime --nocolor | \
	egrep 'AKF|MD5-DIGEST' | \
	sort > $(oam_logfile qcheck)
) \
       2> >(oam_err "qcheck")

oam_log "qcheck complete"

exit 0
