#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

LOGPREFIX=$OAM_LOGDIR

[[ ! -d $LOGPREFIX ]] && mkdir -p $LOGPREFIX

oam_log "oam-glsa start"

# glsa-dumps these lines to stderr, while the actual report goes
# to stdout...
# [A] means this GLSA was marked as applied (injected),
# [U] means the system is not affected and
# [N] indicates that the system might be affected.
# This system is affected by the following GLSAs:

glsa-check --test --verbose  --nocolor all \
       >>${LOGPREFIX}/glsa.log \
       2>&1

oam_log "oam-glsa complete"

if [[ -s ${LOGPREFIX}/glsa.log ]] ; then
    echo "Security issues have been found which may affect this server"
    exit 1
else
    exit 0
fi
