#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

logfile=$(oam_logfile sync)

if [[ -x /usr/bin/layman ]] ; then
    oam_log "layman start"
    # layman spams the error log
    layman --sync=ALL --nocolor \
	   >>$logfile \
	   2>&1
    oam_log "oam-layman complete"
else
    oam_log "layman not installed"
fi

exit 0
