#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

logfile=$(oam_logfile mussh)

cd $(dirname $logfile) || oam_die "failed to chdir to $(dirname $logfile)"

while true ; do
    case $1 in
	-c)
            cmd=$2
            shift 2
            ;;
	-l)
            loginname=$2
            shift 2
            ;;
	*)
            break
            ;;
    esac
done
 
exec \
    screen \
    -d -m -L \
    -S oam-mussh \
    mussh \
    -d 1 \
    -o ConnectTimeout=5 \
    -l ${loginname:-"$USER"} \
    -c "${cmd:-"oam-go"}" \
    -m \
    -h $@

