#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

subdir=$(basename $(oam_logdate))

if [[ -f /etc/make.conf ]] ; then
    makeconf=/etc/make.conf
elif [[ -f /etc/portage/make.conf ]] ; then
    makeconf=/etc/portage/make.conf
fi

cd $OAM_LOGDIR && \
    $OAM_EDITOR_MULTITAB \
	$subdir/{oam,error,glsa,blocks,kernel,merge,sync}.log \
	/etc/portage/package.{keywords,use} $makeconf &

exit 0
