#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

tag=${OAM_TAG:-"merge"}

oam_log "oam ${tag} start $*"

cmdlog=$(oam_mergelogfile cmd)
echo "$@" >>$cmdlog

emerge $@ \
       >>$(oam_mergelogfile merge) \
       2>>$(oam_mergelogfile blocks)

oam_log "oam ${tag} complete"

exit 0
