#!/bin/bash

source /etc/gentoo-oam.conf
source /usr/share/gentoo-oam/gentoo-oam-functions.sh

LOGPREFIX=$OAM_LOGDIR/$(date +%Y%m%d)

[[ ! -d $LOGPREFIX ]] && mkdir -p $LOGPREFIX

oam_log "gentoo-oam V$(oam_version)"

if [[ "$OAM_EMERGE_SYNC" = "1" ]] ; then
    oam_log "oam-sync start"
    PORTAGE_RSYNC_EXTRA_OPTS="--info=progress0,name0,del0" \
    emaint --auto sync \
	   >>${LOGPREFIX}/sync.log \
	   2> >(oam_stripansi | oam_err "sync")
fi

if [[ -x /usr/bin/layman ]] ; then
    oam_log "layman start"
    # layman spams the error log
    layman --sync=ALL --nocolor \
	   >>${LOGPREFIX}/sync.log \
	   2>&1
fi

oam_log "eix-update start"
eix-update --nocolor \
       >>${LOGPREFIX}/sync.log \
       2> >(oam_stripansi | oam_err "eix-update")

remote=/var/cache/eix/remote.tar.bz2
minage=$(( $(date +%s) - ($OAM_EIX_REMOTE_DAYS*24*3600) ))

if [[ "$OAM_EIX_REMOTE" = "1" && -x /usr/bin/layman ]] ; then
    # eix-remote {update1,add1} spam the error log
    if [[ ! -f "$remote" || ( $(stat --format=%Y $remote) -le $minage ) ]] ; then
	for cmd in update1 add1 ; do
	    oam_log "eix-remote $cmd start"
	    eix-remote $cmd \
		       > >(oam_stripansi >>${LOGPREFIX}/sync.log) \
		       2>&1
	done
    else
	days=$(( ( $(date +%s) - $(stat --format=%Y $remote) ) / (24 * 3600) ))
	oam_log "eix-remote not updating - $remote is only $day(s) old"
    fi
fi

oam_log "oam-sync complete"

exit 0
