
.PHONY: all
all:
	@echo "done"

.PHONY: check
check:
	@echo "done"

.PHONY: install
install:
	install -d $(DESTDIR)/usr/share/gentoo-oam
	install gentoo-oam-functions.sh $(DESTDIR)/usr/share/gentoo-oam
	install gentoo-oam-multitail.conf $(DESTDIR)/usr/share/gentoo-oam
	install oam-watch.help $(DESTDIR)/usr/share/gentoo-oam
